
## Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
#spring.redis.database=0
## Redis服务器地址
#spring.redis.host=127.0.0.1
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
#spring.redis.password=root
##连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
## 连接池中的最大空闲连接
#spring.redis.pool.max-idle=8
## 连接池中的最小空闲连接
#spring.redis.pool.min-idle=0
# 连接超时时间（毫秒）
#spring.redis.timeout=0
delay:
  queue:
    project-name: delay-queue-demo

spring:
  redis:
    cluster:
      nodes: 172.18.214.36:7001,172.18.214.36:7002,172.18.214.37:7001,172.18.214.37:7002,172.18.214.38:7001,172.18.214.38:7002
      timeout: 2000
      max-redirects: 8
      password: 123456